--------------------------------------------------------------------------------
-- 01_tables.sql
-- Role-Based / Button-Based Security model for Oracle APEX
-- Author: Abdullah Farooq
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. APP_USERS  -> application login credentials
--------------------------------------------------------------------------------
CREATE TABLE app_users (
    user_id        NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50)    NOT NULL UNIQUE,
    password_hash  VARCHAR2(200)   NOT NULL,      -- store hashed value only, never plain text
    salt           VARCHAR2(100),
    full_name      VARCHAR2(150),
    email          VARCHAR2(150),
    is_active      CHAR(1)         DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
    is_locked      CHAR(1)         DEFAULT 'N' CHECK (is_locked IN ('Y','N')),
    failed_logins  NUMBER          DEFAULT 0,
    last_login_dt  DATE,
    created_by     VARCHAR2(50)    DEFAULT USER,
    created_dt     DATE            DEFAULT SYSDATE,
    updated_by     VARCHAR2(50),
    updated_dt     DATE
);

--------------------------------------------------------------------------------
-- 2. APP_ROLES  -> e.g. ADMIN, MANAGER, USER, VIEWER
--------------------------------------------------------------------------------
CREATE TABLE app_roles (
    role_id        NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name      VARCHAR2(50)    NOT NULL UNIQUE,
    role_desc      VARCHAR2(200),
    is_active      CHAR(1)         DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
    created_dt     DATE            DEFAULT SYSDATE
);

--------------------------------------------------------------------------------
-- 3. APP_USER_ROLES -> many-to-many: a user can hold several roles
--------------------------------------------------------------------------------
CREATE TABLE app_user_roles (
    user_role_id   NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER          NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
    role_id        NUMBER          NOT NULL REFERENCES app_roles(role_id) ON DELETE CASCADE,
    assigned_dt    DATE            DEFAULT SYSDATE,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

--------------------------------------------------------------------------------
-- 4. APP_MENU_ITEMS -> self-referencing tree, drives the APEX side navigation
--                       (Universal Theme "tree based navigation")
--------------------------------------------------------------------------------
CREATE TABLE app_menu_items (
    menu_id        NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_menu_id NUMBER          REFERENCES app_menu_items(menu_id),
    menu_label     VARCHAR2(100)   NOT NULL,
    menu_icon      VARCHAR2(60),          -- e.g. fa-home, fa-users
    target_page_id NUMBER,                -- APEX page number this menu points to
    display_seq    NUMBER          DEFAULT 10,
    is_active      CHAR(1)         DEFAULT 'Y' CHECK (is_active IN ('Y','N'))
);

--------------------------------------------------------------------------------
-- 5. APP_MENU_ROLE_ACCESS -> which role can see which tree node
--------------------------------------------------------------------------------
CREATE TABLE app_menu_role_access (
    menu_access_id NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id        NUMBER          NOT NULL REFERENCES app_menu_items(menu_id) ON DELETE CASCADE,
    role_id        NUMBER          NOT NULL REFERENCES app_roles(role_id) ON DELETE CASCADE,
    CONSTRAINT uq_menu_role UNIQUE (menu_id, role_id)
);

--------------------------------------------------------------------------------
-- 6. APP_COMPONENT_SECURITY -> generic table for page / region / button / item
--                               level security, keyed off an APEX component id
--                               (this is what drives "button-based security")
--------------------------------------------------------------------------------
CREATE TABLE app_component_security (
    security_id    NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id        NUMBER          NOT NULL REFERENCES app_roles(role_id) ON DELETE CASCADE,
    app_id         NUMBER          NOT NULL,     -- APEX application id
    page_id        NUMBER,                       -- APEX page id (null = applies app-wide)
    component_type VARCHAR2(20)    NOT NULL
                     CHECK (component_type IN ('PAGE','REGION','BUTTON','ITEM','COLUMN')),
    component_name VARCHAR2(100)   NOT NULL,     -- static id of the Button/Item/Region
    display_ind    CHAR(1)         DEFAULT 'Y' CHECK (display_ind IN ('Y','N')),
    readonly_ind   CHAR(1)         DEFAULT 'N' CHECK (readonly_ind IN ('Y','N')),
    created_dt     DATE            DEFAULT SYSDATE
);

--------------------------------------------------------------------------------
-- 7. APP_LOGIN_AUDIT -> login attempts, success/failure trail
--------------------------------------------------------------------------------
CREATE TABLE app_login_audit (
    audit_id       NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50),
    attempt_dt     DATE            DEFAULT SYSDATE,
    result         VARCHAR2(20)    CHECK (result IN ('SUCCESS','FAILURE','LOCKED')),
    ip_address     VARCHAR2(50)
);

--------------------------------------------------------------------------------
-- Helpful indexes
--------------------------------------------------------------------------------
CREATE INDEX ix_user_roles_user   ON app_user_roles(user_id);
CREATE INDEX ix_user_roles_role   ON app_user_roles(role_id);
CREATE INDEX ix_menu_parent       ON app_menu_items(parent_menu_id);
CREATE INDEX ix_menu_role_role    ON app_menu_role_access(role_id);
CREATE INDEX ix_comp_sec_lookup   ON app_component_security(role_id, app_id, page_id, component_name);
